// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWiPhKRG10bIo28UvdquKT51KWW76cJw',
    appId: '1:961156032546:android:41a6b58301e07f53dcc27b',
    messagingSenderId: '961156032546',
    projectId: 'gps-tracker-538d4',
    storageBucket: 'gps-tracker-538d4.firebasestorage.app',
    databaseURL: 'https://gps-tracker-538d4-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdqta4QcpaNXuxIpjGac2rGLGTb3B8E3U',
    appId: '1:961156032546:ios:65d254c1e928be7bdcc27b',
    messagingSenderId: '961156032546',
    projectId: 'gps-tracker-538d4',
    storageBucket: 'gps-tracker-538d4.firebasestorage.app',
    iosClientId: '961156032546-ltr3qmgrns4rfmc0ec8uqkq0q3lh2vbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.pamTa',
    databaseURL: 'https://gps-tracker-538d4-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE1Bs6nZEqosxxOiqAqnws9FVpwS8lIrI',
    appId: '1:961156032546:web:b4eb09d619c3188adcc27b',
    messagingSenderId: '961156032546',
    projectId: 'gps-tracker-538d4',
    authDomain: 'gps-tracker-538d4.firebaseapp.com',
    storageBucket: 'gps-tracker-538d4.firebasestorage.app',
    measurementId: 'G-PPXFL534Z3',
    databaseURL: 'https://gps-tracker-538d4-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE1Bs6nZEqosxxOiqAqnws9FVpwS8lIrI',
    appId: '1:961156032546:web:6c2808e65164259fdcc27b',
    messagingSenderId: '961156032546',
    projectId: 'gps-tracker-538d4',
    authDomain: 'gps-tracker-538d4.firebaseapp.com',
    storageBucket: 'gps-tracker-538d4.firebasestorage.app',
    measurementId: 'G-XNEVP54TF6',
    databaseURL: 'https://gps-tracker-538d4-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdqta4QcpaNXuxIpjGac2rGLGTb3B8E3U',
    appId: '1:961156032546:ios:65d254c1e928be7bdcc27b',
    messagingSenderId: '961156032546',
    projectId: 'gps-tracker-538d4',
    storageBucket: 'gps-tracker-538d4.firebasestorage.app',
    iosClientId: '961156032546-ltr3qmgrns4rfmc0ec8uqkq0q3lh2vbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.pamTa',
    databaseURL: 'https://gps-tracker-538d4-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
